FROM node:18.16.1

COPY scripts/install.sh .
RUN ./install.sh

WORKDIR /app

# Configure git
RUN git config --global credential.helper cache

# Clone archiver repo
RUN git clone -b dev https://github.com/shardeum/archive-server.git . \
    && npm install

# apply debugsecrets.patch
RUN git apply debugsecrets.patch

# Build and run
RUN npm run prepare

EXPOSE 4000

CMD ["node", "build/server.js"] 