FROM node:18.16.1

COPY scripts/install.sh .
RUN ./install.sh

WORKDIR /app

# Clone RPC repo
RUN git clone -b dev https://github.com/shardeum/json-rpc-server.git . \
    && npm install

# Apply patches if they exist
COPY patches/json-rpc/* ./patches/
RUN for patch in ./patches/*.patch; do \
      if [ -f "$patch" ]; then \
        git apply "$patch"; \
      fi; \
    done
# Build
RUN npm run compile

EXPOSE 8080

CMD ["node", "dist/src/index.js"] 